<?php

/**
 * BasePublicationSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $publication_id
 * @property integer $subject_id
 * @property Publication $Publication
 * @property Subject $Subject
 * 
 * @method integer            getPublicationId()  Returns the current record's "publication_id" value
 * @method integer            getSubjectId()      Returns the current record's "subject_id" value
 * @method Publication        getPublication()    Returns the current record's "Publication" value
 * @method Subject            getSubject()        Returns the current record's "Subject" value
 * @method PublicationSubject setPublicationId()  Sets the current record's "publication_id" value
 * @method PublicationSubject setSubjectId()      Sets the current record's "subject_id" value
 * @method PublicationSubject setPublication()    Sets the current record's "Publication" value
 * @method PublicationSubject setSubject()        Sets the current record's "Subject" value
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePublicationSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publication_subject');
        $this->hasColumn('publication_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('subject_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Publication', array(
             'local' => 'publication_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Subject', array(
             'local' => 'subject_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}