<?php

/**
 * BaseFacultySchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faculty_id
 * @property integer $school_id
 * @property Faculty $Faculty
 * @property School $School
 * 
 * @method integer       getFacultyId()  Returns the current record's "faculty_id" value
 * @method integer       getSchoolId()   Returns the current record's "school_id" value
 * @method Faculty       getFaculty()    Returns the current record's "Faculty" value
 * @method School        getSchool()     Returns the current record's "School" value
 * @method FacultySchool setFacultyId()  Sets the current record's "faculty_id" value
 * @method FacultySchool setSchoolId()   Sets the current record's "school_id" value
 * @method FacultySchool setFaculty()    Sets the current record's "Faculty" value
 * @method FacultySchool setSchool()     Sets the current record's "School" value
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFacultySchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faculty_school');
        $this->hasColumn('faculty_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('school_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Faculty', array(
             'local' => 'faculty_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('School', array(
             'local' => 'school_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}