<?php

/**
 * BasePublication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $citation
 * @property text $citation_stripped
 * @property integer $publication_date
 * @property integer $publication_type_id
 * @property PublicationType $PublicationType
 * @property Doctrine_Collection $Subjects
 * @property Doctrine_Collection $Facultys
 * @property Doctrine_Collection $PublicationSubject
 * @property Doctrine_Collection $FacultyPublication
 * 
 * @method text                getCitation()            Returns the current record's "citation" value
 * @method text                getCitationStripped()    Returns the current record's "citation_stripped" value
 * @method integer             getPublicationDate()     Returns the current record's "publication_date" value
 * @method integer             getPublicationTypeId()   Returns the current record's "publication_type_id" value
 * @method PublicationType     getPublicationType()     Returns the current record's "PublicationType" value
 * @method Doctrine_Collection getSubjects()            Returns the current record's "Subjects" collection
 * @method Doctrine_Collection getFacultys()            Returns the current record's "Facultys" collection
 * @method Doctrine_Collection getPublicationSubject()  Returns the current record's "PublicationSubject" collection
 * @method Doctrine_Collection getFacultyPublication()  Returns the current record's "FacultyPublication" collection
 * @method Publication         setCitation()            Sets the current record's "citation" value
 * @method Publication         setCitationStripped()    Sets the current record's "citation_stripped" value
 * @method Publication         setPublicationDate()     Sets the current record's "publication_date" value
 * @method Publication         setPublicationTypeId()   Sets the current record's "publication_type_id" value
 * @method Publication         setPublicationType()     Sets the current record's "PublicationType" value
 * @method Publication         setSubjects()            Sets the current record's "Subjects" collection
 * @method Publication         setFacultys()            Sets the current record's "Facultys" collection
 * @method Publication         setPublicationSubject()  Sets the current record's "PublicationSubject" collection
 * @method Publication         setFacultyPublication()  Sets the current record's "FacultyPublication" collection
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePublication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publication');
        $this->hasColumn('citation', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('citation_stripped', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('publication_date', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('publication_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('citation_stripped_index', array(
             'fields' => 
             array(
              'citation_stripped' => 
              array(
              'length' => 50,
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PublicationType', array(
             'local' => 'publication_type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Subject as Subjects', array(
             'refClass' => 'PublicationSubject',
             'local' => 'publication_id',
             'foreign' => 'subject_id'));

        $this->hasMany('Faculty as Facultys', array(
             'refClass' => 'FacultyPublication',
             'local' => 'publication_id',
             'foreign' => 'faculty_id'));

        $this->hasMany('PublicationSubject', array(
             'local' => 'id',
             'foreign' => 'publication_id'));

        $this->hasMany('FacultyPublication', array(
             'local' => 'id',
             'foreign' => 'publication_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}