<?php

/**
 * BaseSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Facultys
 * @property Doctrine_Collection $FacultySchool
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getFacultys()      Returns the current record's "Facultys" collection
 * @method Doctrine_Collection getFacultySchool() Returns the current record's "FacultySchool" collection
 * @method School              setName()          Sets the current record's "name" value
 * @method School              setFacultys()      Sets the current record's "Facultys" collection
 * @method School              setFacultySchool() Sets the current record's "FacultySchool" collection
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Faculty as Facultys', array(
             'refClass' => 'FacultySchool',
             'local' => 'school_id',
             'foreign' => 'faculty_id'));

        $this->hasMany('FacultySchool', array(
             'local' => 'id',
             'foreign' => 'school_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             ));
        $this->actAs($sluggable0);
    }
}