<?php

/**
 * BaseFaculty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $last_name
 * @property string $first_name
 * @property Doctrine_Collection $Publications
 * @property Doctrine_Collection $Schools
 * @property Doctrine_Collection $FacultyPublication
 * @property Doctrine_Collection $FacultySchool
 * 
 * @method string              getLastName()           Returns the current record's "last_name" value
 * @method string              getFirstName()          Returns the current record's "first_name" value
 * @method Doctrine_Collection getPublications()       Returns the current record's "Publications" collection
 * @method Doctrine_Collection getSchools()            Returns the current record's "Schools" collection
 * @method Doctrine_Collection getFacultyPublication() Returns the current record's "FacultyPublication" collection
 * @method Doctrine_Collection getFacultySchool()      Returns the current record's "FacultySchool" collection
 * @method Faculty             setLastName()           Sets the current record's "last_name" value
 * @method Faculty             setFirstName()          Sets the current record's "first_name" value
 * @method Faculty             setPublications()       Sets the current record's "Publications" collection
 * @method Faculty             setSchools()            Sets the current record's "Schools" collection
 * @method Faculty             setFacultyPublication() Sets the current record's "FacultyPublication" collection
 * @method Faculty             setFacultySchool()      Sets the current record's "FacultySchool" collection
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFaculty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faculty');
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('first_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));


        $this->index('name_index', array(
             'fields' => 
             array(
              'last_name' => 
              array(
              ),
              'first_name' => 
              array(
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Publication as Publications', array(
             'refClass' => 'FacultyPublication',
             'local' => 'faculty_id',
             'foreign' => 'publication_id'));

        $this->hasMany('School as Schools', array(
             'refClass' => 'FacultySchool',
             'local' => 'faculty_id',
             'foreign' => 'school_id'));

        $this->hasMany('FacultyPublication', array(
             'local' => 'id',
             'foreign' => 'faculty_id'));

        $this->hasMany('FacultySchool', array(
             'local' => 'id',
             'foreign' => 'faculty_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($softdelete0);
    }
}