<?php

/**
 * BaseSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Publications
 * @property Doctrine_Collection $PublicationSubject
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method Doctrine_Collection getPublications()       Returns the current record's "Publications" collection
 * @method Doctrine_Collection getPublicationSubject() Returns the current record's "PublicationSubject" collection
 * @method Subject             setName()               Sets the current record's "name" value
 * @method Subject             setPublications()       Sets the current record's "Publications" collection
 * @method Subject             setPublicationSubject() Sets the current record's "PublicationSubject" collection
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subject');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Publication as Publications', array(
             'refClass' => 'PublicationSubject',
             'local' => 'subject_id',
             'foreign' => 'publication_id'));

        $this->hasMany('PublicationSubject', array(
             'local' => 'id',
             'foreign' => 'subject_id'));
    }
}