<?php

/**
 * BaseFacultyPublication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faculty_id
 * @property integer $publication_id
 * @property Faculty $Faculty
 * @property Publication $Publication
 * 
 * @method integer            getFacultyId()      Returns the current record's "faculty_id" value
 * @method integer            getPublicationId()  Returns the current record's "publication_id" value
 * @method Faculty            getFaculty()        Returns the current record's "Faculty" value
 * @method Publication        getPublication()    Returns the current record's "Publication" value
 * @method FacultyPublication setFacultyId()      Sets the current record's "faculty_id" value
 * @method FacultyPublication setPublicationId()  Sets the current record's "publication_id" value
 * @method FacultyPublication setFaculty()        Sets the current record's "Faculty" value
 * @method FacultyPublication setPublication()    Sets the current record's "Publication" value
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFacultyPublication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faculty_publication');
        $this->hasColumn('faculty_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('publication_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Faculty', array(
             'local' => 'faculty_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Publication', array(
             'local' => 'publication_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}