# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Faculty Publications Database
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /sfDoctrinePlugin/css/global.css
    - /sfDoctrinePlugin/css/default.css
    - global.css
    - backend.css
    - local-backend.css

  javascripts:
    - jquery-1.5.2.min.js
    - tinymce-3.4.2/tiny_mce.js
    - backend.js

  has_layout:     true
  layout:         layout
