<?php

/**
 * FacultySchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacultySchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacultySchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacultySchool');
    }
}