<?php

/**
 * Faculty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    facpubs2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Faculty extends BaseFaculty
{
  public function __toString()
  {
    return $this->getReversedName();
  }

  public function getReversedName()
  {
    return $this->getLastName() . ', ' . $this->getFirstName();
  }

  public function getPublicationsOrderByCitation()
  {
    $q = Doctrine_Core::getTable('Publication')
      ->createQuery('p')
      ->leftJoin('p.Facultys f')
      ->where('f.id = ?', $this->getId())
      ->orderBy('p.citation_stripped asc')
    ;

    return $q->execute();
  }
}
