<?php

/**
 * FacultyPublicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacultyPublicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacultyPublicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacultyPublication');
    }
}