<?php

/**
 * FacultyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacultyTable extends Doctrine_Table implements ynWidgetAjaxTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacultyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faculty');
    }

  public static function backendIndex( Doctrine_Query $q )
  {
    $f = $q->getRootAlias();

    $q->orderBy( "$f.last_name asc, $f.first_name asc" );

    return $q;
  }

  public function retrieveForYnAjax( $term, $limit = 10, array $not = array() )
  {
    $q = self::getInstance()
      ->createQuery('f')
      ->where('f.deleted_at IS NULL')
      ->andWhere('f.last_name LIKE ?', $term.'%')
      ->orWhere('f.first_name LIKE ?', $term.'%')
      ->limit( $limit )
      ->orderBy('f.last_name, f.first_name ASC')
      ;

    if ( $not ) {
      $q->whereNotIn('f.id', $not);
    }

    return $q->execute();
  }
}