<?php

/**
 * PublicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicationTable extends Doctrine_Table
{
  public function backendIndex( Doctrine_Query $q )
  {
    $p = $q->getRootAlias();

    $q->leftJoin( "$p.PublicationType" );
    $q->leftJoin( "$p.Facultys fac" );
    $q->orderBy( "$p.publication_date desc, $p.citation_stripped asc" );

    return $q;
  }

  /**
   * @param PublicationFrontendFilterForm $filters
   * @return Doctrine_Query
   */
  public function queryFromFrontendFilters( PublicationFrontendFilterForm $filters )
  {
    $q = $this->createQuery('p')
      ->orderBy('p.citation_stripped asc');

    if ( $filters->getValue('q') !== '' && $filters->getValue('q') !== null ) {
      $words = explode( ' ', $filters->getValue('q') );

      foreach ( $words as $w ) {
        $q->andWhere('p.citation_stripped LIKE ?', '%'.$w.'%' );
      }
    }
    
    if ( $filters->getValue('type') !== '' && $filters->getValue('type') !== null ) {
      $q->andWhere('p.publication_type_id = ?', $filters->getValue('type') );
    }

    if ( $filters->getValue('subject') !== '' && $filters->getValue('subject') !== null ) {
      $q->leftJoin('p.Subjects s')
        ->andWhere('s.id = ?', $filters->getValue('subject') );
    }

    if ( $filters->getValue('year') !== '' && $filters->getValue('year') !== null ) {
      $q->andWhere('p.publication_date = ?', $filters->getValue('year') );
    }

    return $q;
  }

  public function findByFaculty( $id )
  {
    $q = $this->createQuery('p')
      ->leftJoin('p.Facultys f')
      ->where('f.id = ?', $id)
      ;

    return $q->execute();
  }

  public static function getInstance()
  {
    return Doctrine_Core::getTable('Publication');
  }
}