<?php

/**
 * PublicationSubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicationSubjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicationSubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicationSubject');
    }
}