<?php

/**
 * SchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('School');
    }

  public static function fetchAllOrdered()
  {
    $q = self::getInstance()->createQuery('s')->orderBy('s.name asc');
    
    return $q->execute();
  }

  public static function findJoinFaculty( $id )
  {
    $q = self::getInstance()->createQuery('s')
      ->where('s.id = ?', $id)
      ->leftJoin('s.Facultys f')
      ->orderBy('f.last_name asc, f.first_name asc')
      ->limit(1)
      ;

    return $q->fetchOne();
  }

  public static function backendIndex( Doctrine_Query $q )
  {
    $r = $q->getRootAlias();

    $q->orderBy( "$r.name asc" );

    return $q;
  }
}