<?php

/**
 * SubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subject');
    }

  public static function backendIndex( Doctrine_Query $q )
  {
    $r = $q->getRootAlias();

    $q->orderBy( "$r.name asc" );

    return $q;
  }
}