generator:
  class: sfDoctrineGenerator
  param:
    model_class:           publication
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          publication
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _save_and_add: { label: Save and create another }
      fields:
        citation_stripped: { label: Citation }
        citation_teaser: { label: Citation }
        publication_type_string: { label: Type }
        faculty_string: { label: Faculty }
        publication_type_id: { label: Type }
        publication_date: { label: Date }
        languages_list: { label: Language }
        subjects_list: { label: Subject }
        facultys_list: { label: Faculty }
      list:
        display:
          - =citation
          - publication_date
        table_method: backendIndex
        max_per_page: 100
      filter:
        display:
          - citation_stripped
      form:    ~
      edit:
        display:
          - citation
          - publication_date
          - languages_list
          - publication_type_id
          - subjects_list
          - _facultys_list
      new:     ~
