# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Faculty Publications
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /tc/drupal.css: { media: all }
    - /tc/drupal-p.css: { media: print }
    - ui-custom/jquery-ui-1.8.12.custom.css
    - global.css
    - frontend.css
    - local-frontend.css

  javascripts:
    - /tc/drupal.js
    - global.js
    - frontend.js

  has_layout:     true
  layout:         layout
